"""
Конфигурационный пакет
"""

from .settings import (
    DATA_CONFIG,
    PREPROCESSING_CONFIG,
    RANDOM_FOREST_CONFIG,
    XGBOOST_CONFIG,
    VISUALIZATION_CONFIG,
    RESULTS_CONFIG,
    CATEGORICAL_FEATURES,
    NUMERICAL_FEATURES,
    TARGET_COLUMN,
    TARGET_MAPPING,
    TARGET_LABELS,
    PLOT_TITLES,
    FEATURE_DESCRIPTIONS,
)

__all__ = [
    'DATA_CONFIG',
    'PREPROCESSING_CONFIG',
    'RANDOM_FOREST_CONFIG',
    'XGBOOST_CONFIG',
    'VISUALIZATION_CONFIG',
    'RESULTS_CONFIG',
    'CATEGORICAL_FEATURES',
    'NUMERICAL_FEATURES',
    'TARGET_COLUMN',
    'TARGET_MAPPING',
    'TARGET_LABELS',
    'PLOT_TITLES',
    'FEATURE_DESCRIPTIONS',
]